import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const UpcomingEventItem = ({ event, onToggleImportant, onEditEvent, onSetReminder, }) => {
    const eventDate = new Date(`${event.date}T00:00:00`);
    const dateLabel = new Intl.DateTimeFormat("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
    }).format(eventDate);
    return (_jsxs("article", { className: "upcoming-event-item", children: [_jsx("div", { className: "upcoming-event-item__accent", style: { backgroundColor: event.color } }), _jsxs("div", { className: "upcoming-event-item__content", children: [_jsxs("div", { className: "upcoming-event-item__top-row", children: [_jsxs("div", { className: "upcoming-event-item__titles", children: [_jsxs("div", { className: "upcoming-event-item__meta", children: [_jsx("span", { className: `upcoming-event-item__badge upcoming-event-item__badge--${event.statusLabel.toLowerCase()}`, children: event.statusLabel }), _jsx("span", { className: "upcoming-event-item__countdown", children: event.countdownLabel })] }), _jsx("h3", { className: "upcoming-event-item__title", children: event.title }), _jsxs("p", { className: "upcoming-event-item__datetime", children: [dateLabel, " \u2022 ", event.startTime, " - ", event.endTime] })] }), _jsxs("div", { className: "upcoming-event-item__flags", children: [event.isImportant && _jsx("span", { className: "upcoming-event-item__flag upcoming-event-item__flag--important", children: "\u2605 Important" }), _jsx("span", { className: "upcoming-event-item__flag upcoming-event-item__flag--color", children: event.color })] })] }), event.description && (_jsx("p", { className: "upcoming-event-item__description", children: event.description })), _jsxs("div", { className: "upcoming-event-item__footer", children: [_jsx("span", { className: "upcoming-event-item__reminder", children: event.reminderLabel }), _jsxs("div", { className: "upcoming-event-item__actions", children: [_jsx("button", { type: "button", className: `upcoming-event-item__action ${event.isImportant ? "is-active" : ""}`, onClick: () => onToggleImportant(event.id), "aria-pressed": event.isImportant, title: event.isImportant ? "Remove important flag" : "Mark as important", children: event.isImportant ? "★" : "☆" }), _jsx("button", { type: "button", className: "upcoming-event-item__action", onClick: () => onEditEvent(event), title: "Edit event", children: "\u270E" }), _jsx("button", { type: "button", className: "upcoming-event-item__action", onClick: () => onSetReminder(event), title: "Set custom reminder", children: "\uD83D\uDD14" })] })] })] })] }));
};
